### ISSUE TITLE
hanspell-ignore 파일 file path 변경 가능하게 세팅

### ISSUE THREAD

**Issue by cheunjm** [9beach/vscode-hanspell#2]
현재 아래 코드와 같이 .hanspell-ignore파일을 user의 process.env.HOME에서 찾고 있는데, 파일을 위치를 vscode workspace내부에서 먼저 찾고, 없으면 process.env.HOME에서 찾을 수 있으면 좋을 것 같습니다.

/** File path of .hanspell-ignore */
  private static readonly path = `${
    process.env.HOME || process.env.USERPROFILE
  }/.hanspell-ignore;

**Comment by 9beach** [comment]
vscode workspace라고 함은 구체적으로 어디일까요? 제가 사실 vscode에 대해 잘 몰라서 여쭈어 봅니다.

**Comment by 9beach** [comment]
오랫동안 회신이 없어서 닫습니다.
